development:
  clients:
    default:
      database: rpg_sheets_api_development
      hosts:
        - localhost:27017


test:
  clients:
    default:
      database: rpg_sheets_api_test
      hosts:
        - localhost:27017
